- id: '1775955710436'
  alias: Great Room Lights Off
  description: ''
  triggers:
  - trigger: time
    at: '22:00:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  conditions:
  - condition: device
    device_id: 00edbf4e08e3e42ab78d2d8df8246311
    domain: media_player
    entity_id: a31c9ad0f81350e416ba939f2814b884
    type: is_off
  actions:
  - action: light.turn_off
    metadata: {}
    target:
      entity_id:
      - light.great_room_floor_lamp_1
      - light.great_room_floor_lamp_2
    data: {}
  mode: single
